"""The kit's reference agent, generated by a local Ollama model instead of Transformers.

Every number we had came from the kit's mock agent, which is a script: it follows the
reference plan exactly and obeys injected text only in four fixed grammars. That makes
it a narrow victim -- it cannot be talked into anything, and it never takes an
unfamiliar-but-legitimate path through a task. A real model can do both, which is what
this adapter lets us measure.

The kit is explicit about what may change: "How the agent *runs* is yours to configure:
precision, device, decode budget, and whether Qwen3's thinking mode is on. What the agent
*is* stays fixed -- same model, same tools, same system prompt, and no safety
instructions added to it." So this module deliberately owns nothing but the generation
call. The system prompt, the tool cards and the output parser are imported from the
kit's own Hugging Face adapter, and the message layout is copied from it line for line.
Hardening the agent here would move work out of the defense being judged.

Two deviations from the official configuration, both declared in the report:
  * the model -- whatever is installed locally (qwen3.5:9b here) rather than Qwen3-8B;
  * the runtime -- Ollama serves a quantized build, where the kit's adapter loads full
    weights through Transformers.

This is evaluation tooling. It lives outside src/haris on purpose: the defense declares
`models: []` and runs no model on its decision path.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Any

from sentinel.agent.base import AgentContext, Feedback
from sentinel.core.actions import CandidateAction
from sentinel.models.base import ModelAdapter, ModelError, TurnHints
from sentinel.models.hf_adapter import SYSTEM_PROMPT, parse_action, tool_card

DEFAULT_MODEL = os.environ.get("HARIS_AGENT_MODEL", "qwen3.5:9b")
DEFAULT_HOST = os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434")

# Mirrors HFModelAdapter's defaults so the only difference is the runtime.
MAX_NEW_TOKENS = 768
MAX_CONTEXT_CHARS = 12_000
# Greedy decoding, as HFModelAdapter's do_sample=False. The seed pins what little
# nondeterminism a quantized GPU runtime still has, so reruns are comparable.
SEED = 7

# Measured, not guessed: a worst-case prompt -- every tool in a domain plus the full
# 12,000-character history window -- is 6,117 tokens under this model's own tokenizer
# (enterprise; finance 5,972, SOC 6,001). Ollama sizes its default window from VRAM, and
# on an 8 GB GPU that default is 4,096. Ollama drops the FRONT of an over-long prompt,
# which is the system prompt and the tool list: the agent would silently stop being the
# reference agent partway through a scenario. An earlier run of ours was exposed to
# exactly this and was discarded. 16,384 leaves room for history that tokenizes worse
# than prose, such as base64, and costs nothing here -- the 9.7B model already spills
# past 8 GB at either size and runs at the same ~20 tokens/s.
WORST_CASE_PROMPT_TOKENS = 6_117
NUM_CTX = 16_384

# The model's Modelfile ships its own sampling defaults (temperature 1, presence_penalty
# 1.5, top_k 20, top_p 0.95). A presence penalty still reshapes the logits under greedy
# decoding, so overriding temperature alone left the agent decoding differently from the
# reference adapter. Every penalty is pinned to neutral here.
NEUTRAL_DECODING = {
    "temperature": 0,
    "presence_penalty": 0,
    "frequency_penalty": 0,
    "repeat_penalty": 1,
}


class OllamaModelAdapter(ModelAdapter):
    name = "ollama"

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        host: str = DEFAULT_HOST,
        max_new_tokens: int = MAX_NEW_TOKENS,
        max_context_chars: int = MAX_CONTEXT_CHARS,
        enable_thinking: bool = False,
        seed: int = SEED,
        num_ctx: int = NUM_CTX,
        timeout_s: float = 600.0,
    ) -> None:
        if num_ctx < WORST_CASE_PROMPT_TOKENS + max_new_tokens:
            raise ValueError(
                f"num_ctx={num_ctx} cannot hold a worst-case prompt ({WORST_CASE_PROMPT_TOKENS} tokens) "
                f"plus {max_new_tokens} output tokens; Ollama would silently drop the system prompt"
            )
        self.model = model
        self._url = host.rstrip("/") + "/api/chat"
        self._max_new_tokens = max_new_tokens
        self._max_context_chars = max_context_chars
        self._enable_thinking = enable_thinking
        self._seed = seed
        self._num_ctx = num_ctx
        self._timeout_s = timeout_s
        self._goal = ""
        self._tools: list[dict[str, Any]] = []

    def start_turn(self, goal: str, hints: TurnHints) -> None:
        self._goal = goal
        # The reference plan is a simulator affordance for the mock only. A real agent
        # that saw it would be solving a different, much easier problem.
        self._tools = hints.tools

    def _messages(self, context: AgentContext) -> list[dict[str, str]]:
        # Copied from HFModelAdapter._messages so both runtimes see the same prompt.
        history = "\n".join(f"[{obs.kind}] {obs.text}" for obs in context.observations)
        history = history[-self._max_context_chars :]
        tools = json.dumps([tool_card(t) for t in self._tools])
        return [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Tools: {tools}\nGoal: {self._goal}\nHistory:\n{history}"},
        ]

    def _generate(self, messages: list[dict[str, str]]) -> str:
        body = {
            "model": self.model,
            "messages": messages,
            "stream": False,
            "think": self._enable_thinking,
            "options": {
                **NEUTRAL_DECODING,
                "seed": self._seed,
                "num_predict": self._max_new_tokens,
                "num_ctx": self._num_ctx,
            },
        }
        request = urllib.request.Request(
            self._url, json.dumps(body).encode("utf-8"), {"content-type": "application/json"}
        )
        try:
            with urllib.request.urlopen(request, timeout=self._timeout_s) as response:
                payload = json.load(response)
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            raise ModelError(f"ollama unavailable at {self._url}: {exc}") from exc
        if "error" in payload:
            raise ModelError(f"ollama error: {payload['error']}")
        return str(payload.get("message", {}).get("content", ""))

    def propose(self, context: AgentContext) -> CandidateAction:
        return parse_action(self._generate(self._messages(context)))

    def observe(self, feedback: Feedback) -> None:
        return None


def factory(model: str = DEFAULT_MODEL, **kwargs: Any) -> Any:
    """A zero-argument factory, as RunConfig.model_factory expects."""

    def build() -> OllamaModelAdapter:
        return OllamaModelAdapter(model, **kwargs)

    return build
